options:
  logging: CLOUD_LOGGING_AND_CLOUD_STORAGE
  logs_bucket: "gs://flash-crawler-400019-build-logs"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/flash-crawler-400019/auto-committer:v1.0.0"
      - "--build-arg"
      - "GIT_PAT=$$GIT_PAT"
      - "."
    secretEnv:
      - "GIT_PAT"

availableSecrets:
  secretManager:
    - versionName: projects/flash-crawler-400019/secrets/GIT_PAT/versions/1
      env: "GIT_PAT"
