options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "build"
      - "-t"
      - "gcr.io/flash-crawler-400019/auto-committer:v1.0.0"
      - "--build-arg"
      - "GIT_PAT=$$GIT_PAT"
      - "."
    secretEnv: ["GIT_PAT"]

availableSecrets:
  secretManager:
    - versionName: projects/624418733426/secrets/GIT_PAT/versions/1
      env: "GIT_PAT"
