options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker build -t gcr.io/flash-crawler-400019/commiter:latest --build-arg GIT_PAT=$$GIT_PAT ."
    secretEnv: ["GIT_PAT"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/flash-crawler-400019/commiter:latest"

availableSecrets:
  secretManager:
    - versionName: projects/624418733426/secrets/GIT_PAT/versions/2
      env: "GIT_PAT"
